### PR TITLE
Fix support for newer TypeScript and named imports

### LINKED ISSUE #186: swagger-parser `10.0.3` version is not compatible with `typescript` version `4.4.2`
## Description
Dependabot created a [PR](https://github.com/SAP/cloud-sdk-js/pull/1561) for updating `typescript` version to `4.4.2`, which failed due to the error below:

```
TypeError: Class is not a constructor

    at resolve (/.../node_modules/@apidevtools/json-schema-ref-parser/lib/index.js:162:18)
```

## How to reproduce
1. update `typescript` version to `4.4.2`.
2. run the following code and see errors
```typescript
  async resolve(document); // typed as `OpenAPIV3.Document`
```

## Expected behaviour
The type error is fixed.

## Additional information
It's working with `typescript` version `4.3.5`.

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #186
I did my best to avoid breaking changes, tests seem to pass, so I don't expect that semver major will be necessary for this.

### CODE REVIEW

File: lib/index.d.ts [hunk 1]
```diff
@@ -437,3 +435,181 @@ declare namespace SwaggerParser {
...
+ * Parses, dereferences, and validates the given Swagger API.
+ * Depending on the options, validation can include JSON Schema validation and/or Swagger Spec validation.
+ *
+ * See https://apitools.dev/swagger-parser/docs/swagger-parser.html#validateapi-options-callback
+ *
+ * @param api An OpenAPI definition, or the file path or URL of an OpenAPI definition. See the `parse` method for more info.
+ * @param options (optional)
+ * @param callback (optional) A callback that will receive the dereferenced OpenAPI definition
+ */
+export function validate(api: string | OpenAPI.Document, callback: SwaggerParser.ApiCallback): void;
```
Comment (kibertoad) [inline lib/index.d.ts:449]: Unfortunately, I had to duplicate the definition. I am not aware of any other way to expose methods both as part of a class, and as something that can be accessed via named import.

**Review by philsturgeon — APPROVED** [review]

**Comment by philsturgeon** [comment]
Cracking, thank you!

**Comment by mnMomma** [comment]
[open]()
